# Create DATABASE payroll
CREATE DATABASE payroll;
USE payroll;

# Create PERSONAL_INFORMATIONS Table
CREATE TABLE PERSONAL_INFORMATIONS (
 GENDER VARCHAR(255) NOT NULL,
 ETHNICITY VARCHAR(255) NOT NULL,
 EMPLOYEE_NO INT PRIMARY KEY NOT NULL
);			

# Create YEAR Table
CREATE TABLE YEAR (
  PAY_YEAR INT NOT NULL,
  EMPLOYEE_NO INT NOT NULL,
  FOREIGN KEY (EMPLOYEE_NO) REFERENCES PERSONAL_INFORMATIONS (EMPLOYEE_NO)
);

# Create DEPARTMENT Table
CREATE TABLE DEPARTMENT (
  DEPARTMENT_NO INT NOT NULL,
  DEPARTMENT_TITLE CHAR(255) NOT NULL,
  EMPLOYEE_NO INT NOT NULL,
  FOREIGN KEY (EMPLOYEE_NO) REFERENCES PERSONAL_INFORMATIONS (EMPLOYEE_NO)
);

# Create EMPLOYMENT Table
CREATE TABLE EMPLOYMENT (
  JOB_CLASS_PGRADE CHAR(255) NOT NULL,
  JOB_TITLE CHAR(255) NOT NULL,
  EMPLOYMENT_TYPE CHAR(255) NOT NULL,
  JOB_STATUS CHAR(255) NOT NULL,
  EMPLOYEE_NO INT NOT NULL,
  FOREIGN KEY (EMPLOYEE_NO) REFERENCES PERSONAL_INFORMATIONS (EMPLOYEE_NO)
);

# Create PAY Table
CREATE TABLE PAY (
  REGULAR_PAY DECIMAL NOT NULL,
  OVERTIME_PAY DECIMAL NOT NULL,
  ALL_OTHER_PAY DECIMAL NOT NULL,
  TOTAL_PAY DECIMAL NOT NULL,
  EMPLOYEE_NO INT NOT NULL,
  FOREIGN KEY (EMPLOYEE_NO) REFERENCES PERSONAL_INFORMATIONS (EMPLOYEE_NO)
);

# Create RETIREMENT_CONTRIBUTIONS Table
CREATE TABLE RETIREMENT_CONTRIBUTIONS (
CITY_RETIREMENT_CONTRIBUTIONS DECIMAL NOT NULL,
BENEFIT_PAY DECIMAL NOT NULL,
EMPLOYEE_NO INT NOT NULL,
FOREIGN KEY (EMPLOYEE_NO) REFERENCES PERSONAL_INFORMATIONS (EMPLOYEE_NO)
);

